adminapp/urls.py
from django.urls import re_path


import adminapp.views as adminapp

from .apps import AdminappConfig

app_name = AdminappConfig.name

urlpatterns = [

    re_path(r"^$", adminapp.admin_main, name="admin_main"),
    re_path(r"^users/create/$", adminapp.user_create, name="user_create"),
    re_path(r"^users/read/$", adminapp.UsersListView.as_view(), name="users"),
    re_path(r"^users/update/(?P<pk>\d+)/$", adminapp.user_update, name="user_update"),
    re_path(r"^users/delete/(?P<pk>\d+)/$", adminapp.user_delete, name="user_delete"),
    re_path(r"^categories/create/$", adminapp.ProductCategoryCreateView.as_view(), name="category_create"),
    re_path(r"^categories/read/$", adminapp.categories, name="categories"),
    re_path(r"^categories/update/(?P<pk>\d+)/$", adminapp.ProductCategoryUpdateView.as_view(), name="category_update"),
    re_path(r"^categories/delete/(?P<pk>\d+)/$", adminapp.ProductCategoryDeleteView.as_view(), name="category_delete"),
    re_path(r"^products/create/category/(?P<pk>\d+)/$", adminapp.product_create, name="product_create"),
    re_path(r"^products/read/category/(?P<pk>\d+)/$", adminapp.products, name="products"),
    re_path(r"^products/read/(?P<pk>\d+)/$", adminapp.ProductDetailView.as_view(), name="product_read"),
    re_path(r"^products/update/(?P<pk>\d+)/$", adminapp.product_update, name="product_update"),
    re_path(r"^products/delete/(?P<pk>\d+)/$", adminapp.product_delete, name="product_delete"),
]

authnapp/urls.py
from django.urls import re_path

import authnapp.views as authnapp
from authnapp.apps import AuthnappConfig

app_name = AuthnappConfig.name

urlpatterns = [
    re_path(r"^login/$", authnapp.login, name="login"),
    re_path(r"^logout/$", authnapp.logout, name="logout"),
    re_path(r"^register/$", authnapp.register, name="register"),
    re_path(r"^edit/$", authnapp.edit, name="edit"),
    re_path(r"^verify/(?P<email>.+)/(?P<activation_key>\w+)/$", authnapp.verify, name="verify"),
]

basketapp/urls.py
from django.urls import re_path

import basketapp.views as basketapp
from basketapp.apps import BasketappConfig

app_name = BasketappConfig.name

urlpatterns = [
    re_path(r"^$", basketapp.basket, name="view"),
    re_path(r"^add/(?P<pk>\d+)/$", basketapp.basket_add, name="add"),
    re_path(r"^remove/(?P<pk>\d+)/$", basketapp.basket_remove, name="remove"),
    re_path(r"^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$", basketapp.basket_edit, name="edit"),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path, re_path

import mainapp.views as mainapp

urlpatterns = [
    re_path(r"^$", mainapp.main, name="main"),
    re_path(r"^products/", include("mainapp.urls", namespace="products")),
    re_path(r"^contact/", mainapp.contact, name="contact"),
    path("", include("social_django.urls", namespace="social")),
    re_path(r"^auth/", include("authnapp.urls", namespace="auth")),
    re_path(r"^basket/", include("basketapp.urls", namespace="basket")),
    re_path(r"^order/", include("ordersapp.urls", namespace="order")),
    re_path(r"^admin/", include("adminapp.urls", namespace="admin")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r"^__debug__/", include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import re_path

import mainapp.views as mainapp

from .apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [

    re_path(r"^$", mainapp.products, name="index"),
    re_path(r"^category/(?P<pk>\d+)/$", mainapp.products, name="category"),
    re_path(r"^product/(?P<pk>\d+)/$", mainapp.product, name="product"),
    re_path(r"^category/(?P<pk>\d+)/page/(?P<page>\d+)/$", mainapp.products, name="page"),

]

ordersapp/urls.py
from django.urls import re_path

import ordersapp.views as ordersapp
from ordersapp.apps import OrdersappConfig

app_name = OrdersappConfig.name

urlpatterns = [
    re_path(r"^$", ordersapp.OrderList.as_view(), name="orders_list"),
    re_path(r"^create/$", ordersapp.OrderItemsCreate.as_view(), name="order_create"),
    re_path(r"^read/(?P<pk>\d+)/$", ordersapp.OrderRead.as_view(), name="order_read"),
    re_path(r"^update/(?P<pk>\d+)/$", ordersapp.OrderItemsUpdate.as_view(), name="order_update"),
    re_path(r"^delete/(?P<pk>\d+)/$", ordersapp.OrderDelete.as_view(), name="order_delete"),
    re_path(r"^forming/complete/(?P<pk>\d+)/$", ordersapp.order_forming_complete, name="order_forming_complete"),
    re_path(r"^product/(?P<pk>\d+)/price/$", ordersapp.get_product_price),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="имя", max_length=64, unique=True)
    description = models.TextField(verbose_name="описание", blank=True)
    is_active = models.BooleanField(verbose_name="категория активна", default=True, db_index=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="имя продукта", max_length=128)
    image = models.ImageField(upload_to="products_images", blank=True)
    short_desc = models.CharField(verbose_name="краткое описание продукта", max_length=60, blank=True)
    description = models.TextField(verbose_name="описание продукта", blank=True)
    price = models.DecimalField(verbose_name="цена продукта", max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name="количество на складе", default=0)
    is_active = models.BooleanField(verbose_name="продукт активен", default=True, db_index=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by("category", "name")


class Contact(models.Model):
    phone = models.CharField(max_length=50, verbose_name="номер телефона")
    email = models.EmailField(max_length=254, verbose_name="электронная почта")
    city = models.CharField(max_length=128, default="Москва", verbose_name="город")
    address = models.CharField(max_length=254, verbose_name="адресс")

    def __str__(self):
        return f"{self.pk} {self.email}"

mainapp/views.py
import random

from django.conf import settings
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from .models import Contact, Product, ProductCategory


def main(request):
    title = "главная"
    products = Product.objects.filter(is_active=True, category__is_active=True)[:3]
    content = {"title": title, "products": products, "media_url": settings.MEDIA_URL}
    return render(request, "mainapp/index.html", content)


# def get_hot_product():
#     products = Product.objects.filter(is_active=True, category__is_active=True)
#     return random.sample(list(products), 1)[0]


# def get_same_products(hot_product):
#     same_products = Product.objects.filter(category=hot_product.category, is_active=True).exclude(pk=hot_product.pk)[:3]
#     return same_products


def get_hot_product_list():
    products = Product.objects.filter(is_active=True, category__is_active=True).select_related("category")
    hot_product = random.sample(list(products), 1)[0]
    hot_list = products.exclude(pk=hot_product.pk)[:3]
    return (hot_product, hot_list)


def products(request, pk=None, page=1):
    title = "продукты"
    links_menu = ProductCategory.objects.filter(is_active=True)

    if pk is not None:
        if str(pk) == str(0):
            category = {"pk": 0, "name": "все"}
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by("price")
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by(
                "price"
            )

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            "title": title,
            "links_menu": links_menu,
            "category": category,
            "products": products_paginator,
            "media_url": settings.MEDIA_URL,
        }
        return render(request, "mainapp/products_list.html", content)
    # hot_product = get_hot_product()
    # same_products = get_same_products(hot_product)
    hot_product, same_products = get_hot_product_list()
    content = {
        "title": title,
        "links_menu": links_menu,
        "same_products": same_products,
        "media_url": settings.MEDIA_URL,
        "hot_product": hot_product,
    }
    return render(request, "mainapp/products.html", content)


def product(request, pk):
    title = "продукты"
    content = {
        "title": title,
        "links_menu": ProductCategory.objects.filter(is_active=True),
        "product": get_object_or_404(Product, pk=pk),
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "mainapp/product.html", content)


def contact(request):
    title = "о нас"
    visit_date = timezone.now()
    locations = Contact.objects.all()
    content = {"title": title, "visit_date": visit_date, "locations": locations}
    return render(request, "mainapp/contact.html", content)

mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    <li>
        <a href="{% url 'products:category' pk=0 %}"
            class="{% if request.resolver_match.kwargs.pk == 0 %}active{% endif %}">
            все
        </a>
    </li>
    {% for link in links_menu %}
    <li>
        <a href="{% url 'products:category' link.pk %}"
            class="{% if request.resolver_match.kwargs.pk == link.pk %}active{% endif %}">
            {{ link.name }}
        </a>
    </li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_menu.html
<a href="{% url 'main' %}" class="logo"></a>
<ul class="menu">
    <li>
        <a href="{% url 'main' %}" class="{% if request.resolver_match.url_name == 'main' %}active{% endif %}">
            домой
        </a>
    </li>
    <li>
        <a href="{% url 'products:index' %}"
            class="{% if request.resolver_match.namespace == 'products' %}active{% endif %}">
            продукты
        </a>
    </li>
    <li>
        <a href="{% url 'contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
            контакты
        </a>
    </li>
    {% if user.is_authenticated %}
    <li>
        <div class="dropdown">
            <a class="dropdown-toggle" href="" data-toggle="dropdown" id="dropdownMenuButton" aria-haspopup="true"
                aria-expanded="false">
                {{ user.first_name|default:'Пользователь' }}
                <span class="caret"></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'auth:edit' %}">{{ "профиль"|upper }}</a>
                <a class="dropdown-item" href="{% url 'order:orders_list' %}">{{ "Кабинет заказов"|upper }}</a>
            </div>
        </div>
    </li>
    {% endif %}
    {% if user.is_superuser %}
    <li>
        <a href="{% url 'admin:users' %}">админка</a>
    </li>
    {% endif %}
    <li>
        {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
        <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>
</ul>
<a href="#" class="search"></a>
<a href="{% url 'basket:view' %}" class="basket">
    <span>
        {% if basket %}
        {{ basket.0.total_cost|floatformat:0 }} руб ({{ basket.0.total_quantity }} шт)
        {% endif %}
    </span>
</a>